version: 0.1

phases:
  build:
    commands:
      - npm install
      - nmp run webpack

artifacts:
  files:
    - index.html
    - favicon.ico
    - images/*
    - styles/*
    - dist/bundel.js
